### ISSUE TITLE
CSS box model

### ISSUE THREAD

**Issue by SergeyHovh** [SergeyHovh/GrocerEase#33]
**Is your feature request related to a problem? Please describe.**
As an intern, I need to understand the CSS box model to control the spacing and layout of HTML elements effectively.

**Describe the solution you'd like**
I'd like to create a GitHub issue to guide the intern in experimenting with the CSS box model. The specific solution involves the following steps:

Create an HTML page with multiple elements (e.g., divs, paragraphs, headings).
Use CSS to apply margin, padding, and border properties to these elements.
Observe how these properties impact the spacing and layout of elements.
This issue will help the intern gain a clear understanding of the CSS box model and its practical applications.

**Comment by Mstanic05** [comment]
Can you assign this to me!
