### ISSUE TITLE
CSS Transitions

### ISSUE THREAD

**Issue by SergeyHovh** [SergeyHovh/GrocerEase#37]
**Is your feature request related to a problem? Please describe.**
As an intern, I need to learn how to add specific CSS transitions to elements on a web page to create interactive effects.

**Describe the solution you'd like**
I'd like to create a GitHub issue with precise guidance to help the intern apply CSS transitions. The specific solution involves the following steps:

1. Use the existing HTML and CSS code.
2. Select the "Button" element with the class "btn" in your HTML.
3. Create a CSS transition that makes the button change its background color when a user hovers over it.
4. The transition duration should be 0.5 seconds.
5. The transition timing function should be "ease-in-out."
6. The background color should change from the current color to a different color of your choice.
7. Test the transition by hovering over the button in a browser.

This issue will ensure the intern learns how to apply precise CSS transitions to create interactive and engaging effects on a web page.

**Describe alternatives you've considered**
No specific alternatives are considered for this issue. The goal is to provide a task that helps the intern practice creating specific CSS transitions.

**Additional context**
N/A

**Comment by Mstanic05** [comment]
Can you assign this to me!
